### ISSUE TITLE
API endpoint error 

### ISSUE THREAD

**Issue by hluaces** [namecheap/ssl-whmcs#80]
Hey there,

A few weeks ago there's been some kind of incident which forced Namecheap to put CloudFlare in front of part of their web services.

This had some unpredicted consequences on this module.

To be precise, check the following code:

https://github.com/namecheap/ssl-whmcs/blob/89046b1068d18f82fa062650da66b4bed2e988ef/modules/servers/namecheapssl/namecheapssl.php#L284

That code is querying and endpoint protected by CloudFlare's security measures. This means that some requests might be filtered and presented with a "Fill this captcha in order to continue page".

As you might probably guess, that is a non-compliant XML response, which makes the module unable to operate.

Either the module should be able to report and log this incident or the CloudFlare protection should be removed from this API (which is the option that makes more sense to me).

Best regards,
Héctor

**Comment by jas8522** [comment]
@hluaces Namecheap SSL support team has indicated that they've added `https://www.namecheap.com/syndicated/ssl-certificates/get-type-list.aspx` to the Cloudflare exceptions list to prevent captcha triggering. I've commented out the hard coded variable from our module code and will test it out upon next SSL order.

Hopefully it's fixed!

**Comment by hluaces** [comment]
Hey, @jas8522 , they've already answered my initial ticket aswell.

Thank you for bringing this issue to their attention.

Regards!
